### ISSUE TITLE
Sugiro adicionar node_module em uma pasta gitignore 

### ISSUE THREAD

**Issue by mtlouzada** [JoaoEstevam01/Aplicacao-de-Juros#1]
#### Uma boa pratica ao upar seus projetos, é adicionar as dependências em uma pastar gitignore para evitar redundâncias e melhorar performance.

OBS: Caso seja a primeira vez que esteja vendo isso, você pode conferir esse vídeo para aprender como fazer. [Gitignore](https://www.youtube.com/watch?v=pNLb7M-UzO8&t=159s)

**Comment by JoaoEstevam01** [comment]
Adição e atualização do .gitignore e da pasta. Obrigado pela dica!
